#!/bin/bash

# Delete every local branches except master
git branch -a | grep -v -e remotes -e master | sed 's/^[* ] //' | xargs git branch -D

# Create the zip archive
zip -r ubbleai-interview.zip . --exclude=*local_volumes*
