# Generated by Django 2.1.7 on 2020-09-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlestreamiteration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_iterations', to='ubble.StreamerSession', verbose_name='Streamer Session'),
        ),
    ]
