# Generated by Django 2.1.7 on 2020-09-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_auto_20200917_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlestreamiteration',
            name='detected_face_url',
            field=models.URLField(default='', verbose_name='Detected face image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singlestreamiteration',
            name='output_frame_url',
            field=models.URLField(verbose_name='Output frame image URL'),
        ),
    ]
